### ISSUE TITLE
getting a parallax error on startup, tried everything to fix it but nothing helped

### ISSUE THREAD

**Issue by Geplest** [ballisticfox/RSS-Reborn#13]
Love RSS Reborn as a whole by the way

**Comment by ballisticfox** [comment]
This is due to parallax checking for default parallax configs while rss-reborn provides its own configs.

You can create a empty dummy config at the location is specifies to make it happy.

**Comment by Geplest** [comment]
i re-installed every mod before i saw your reply earlier and it worked somehow. Thanks alot though
