### ISSUE TITLE
Axial tilt

### ISSUE THREAD

**Issue by Geplest** [ballisticfox/RSS-Reborn#16]
Will there ever be accurate axial tilt implemented? Or atleast will there be a config made for RSS to work with axial tilt mods? I really hope so since Principia is the only option at the moment, but Principia also gives n-body physics mod, which me and others don't want.

**Comment by ballisticfox** [comment]
There are currently no working axial tilt mods other than principia.

**Comment by Geplest** [comment]
Oh, alright i understand. Thanks for your response
