### ISSUE TITLE
Install instructions incorrect

### ISSUE THREAD

**Issue by DTA666-sys** [ballisticfox/RSS-Reborn#17]
"Install EVE and Scatterer from blackrack's [patreon](https://www.patreon.com/blackrack)."

There are no links to download anything on his patreon other than volumetric clouds which is a paid mod.

**Comment by ballisticfox** [comment]
RSS-Reborn's RSSVE-Configs and RSSVE-Textures requires the paid versions of EVE and Scatterer.
You can technically run RSS-Reborn with RO-RSSVE though if you can't pay for the volumetric version of EVE and Scatterer.

**Comment by DTA666-sys** [comment]
Eve and scatterer don't exist anymore for download, you could check his patreon, you have dead links in your install instructions. I talked to him about this. they are only included in the volumetric clouds release.  so if you want RSS reborn to work currently, you need to buy volumetric clouds.

It's odd that your mod is locked behind someone else's paywall. very odd.

**Comment by ballisticfox** [comment]
1. EVE and scatterer still exist in these repos:
https://github.com/LGhassen/EnvironmentalVisualEnhancements
https://github.com/LGhassen/Scatterer
With the latest releases being the non-volumetric versions.

2. Which links exactly are dead?

3. Somewhat correct, but I think you're misunderstanding what exactly RSS-Reborn is.

EVE/Scatterer/Parallax are examples of _mods_, they take months to years to code and debug and allow the game to do something previously impossible, and in the case of EVE/Scatterer and Parallax, they may go through a paid testing period.
RSS-Reborn and RO-RSS are examples of _configs_, their job is just to specifically tell KSP and the associated mods you have installed what to do. In the case of RSS-Reborn that's best replicating our real solar system at its full scale.
With this knowledge the case of 
> It's odd that your mod is locked behind someone else's paywall. very odd.

is its not odd at all, without the volumetric clouds mods, RSSVE-Configs is merely a text file with a bunch of instructions the game has absolutely no clue what to do with, of course it depends on the volumetric version of EVE.

**Comment by DTA666-sys** [comment]
3. Install EVE and Scatterer from blackrack's [patreon](https://www.patreon.com/blackrack).

a. Do not use StockVolumetricClouds

b. Do not use StockScattererConfigs

These are your install instructions and you know that.  why are you acting like this?

https://github.com/RSS-Reborn/RSS-Reborn/wiki/Installation

I'm not letting you waste more of my time.

**Comment by Badfish266** [comment]
Won't fix

**Comment by DTA666-sys** [comment]
won't fix.
