### ISSUE TITLE
I load the game but get stuck on an infinite black loading screen with spinning planets 

### ISSUE THREAD

**Issue by shujijiangya** [ballisticfox/RSS-Reborn#5]
https://imgur.com/a/vbbpgPi

**Comment by ballisticfox** [comment]
Upload your logs

**Comment by zhouyiqing0304** [comment]
@shujijiangya 突然发现一个很严峻的问题
为啥玩这个的中国人那么多

**Comment by zhouyiqing0304** [comment]
我就没有啊

**Comment by denshustanov** [comment]
I have the same issue although I can hear start menu music.
Logs folder in game installation dir: [Logs.zip](https://github.com/user-attachments/files/16943696/Logs.zip).

Completely removing parallax resolved the problem but now I have an error from compernicus and stock Kerbin spinning in the menu background. Looks like I messed up with rss configs

**Comment by denshustanov** [comment]
> I have the same issue although I can hear start menu music. Logs folder in game installation dir: [Logs.zip](https://github.com/user-attachments/files/16943696/Logs.zip).
> 
> Completely removing parallax resolved the problem but now I have an error from compernicus and stock Kerbin spinning in the menu background. Looks like I messed up with rss configs

Well it seems I've mixed assets from github and google docs versions by accident. I walked through the installation flow again and now everything works as it supposed
