### ISSUE TITLE
Stuck on the loading screen

### ISSUE THREAD

**Issue by somanyfriedpotato** [ballisticfox/RSS-Reborn#7]
![image](https://github.com/user-attachments/assets/312f9eb0-6e42-420f-b206-e4438d8b0cf8)
My game is stuck on this loading screen, i can hear music but it's stuck on this loading screen. How i can fix it?

**Comment by ballisticfox** [comment]
Send your logs

**Comment by somanyfriedpotato** [comment]
[KSP.log](https://github.com/user-attachments/files/17100293/KSP.log)
here it is

**Comment by ballisticfox** [comment]
https://github.com/RSS-Reborn/RSS-Reborn/wiki/Installation

Verify you've completed step 1.

```
Remove the following folders from your GameData:

    EnvironmentalVisualEnhancements
    Kopernicus
    Parallax_StockTextures
    RSS-Textures
    RSSVE
    RealSolarSystem
    Scatterer
```

RealSolarSystem and RSSVE were found in your GameData and can cause problems with bodies failing to load.

Remove those two folders and ideally the issue should be resolved.

**Comment by somanyfriedpotato** [comment]
ok

**Comment by somanyfriedpotato** [comment]
Thanks it worked

**Comment by somanyfriedpotato** [comment]
thanks

**Comment by somanyfriedpotato** [comment]
okay it loaded recently but with texture pack error and i fix it now it doesn't work

**Comment by somanyfriedpotato** [comment]
![image](https://github.com/user-attachments/assets/01778d56-ec13-482d-a43c-de588fcdefe9)
is it a problem?

**Comment by somanyfriedpotato** [comment]
![image](https://github.com/user-attachments/assets/5fc9dca1-874c-423a-b82d-49725ba40890)
it didn't work

**Comment by somanyfriedpotato** [comment]
so i installed the kopernicus fork hope it will work

**Comment by somanyfriedpotato** [comment]
i deleted it again cuz it didn't work
and i will try again
UPDATE : it didn't work

**Comment by ballisticfox** [comment]
https://github.com/ballisticfox/Kopernicus/releases/tag/release-11F
You download Kopernicus from here correct?

**Comment by somanyfriedpotato** [comment]
yes

**Comment by somanyfriedpotato** [comment]
oh no i will download from there

**Comment by somanyfriedpotato** [comment]
yes

**Comment by somanyfriedpotato** [comment]
so it says parallax error at start

**Comment by somanyfriedpotato** [comment]
so i say if you can send me a zip file of all the mods i need?

**Comment by somanyfriedpotato** [comment]
yes

**Comment by somanyfriedpotato** [comment]
ye
