### ISSUE TITLE
Textures went error

### ISSUE THREAD

**Issue by zhouyiqing0304** [ballisticfox/RSS-Reborn#9]
![image](https://github.com/user-attachments/assets/e7036df2-20c4-4000-9d45-cf43a63b035d)

idk what happened to that

**Comment by zhouyiqing0304** [comment]
![image](https://github.com/user-attachments/assets/4c676c42-6aa7-4d01-a35a-075f763e3baf)

**Comment by ballisticfox** [comment]
This is a bug with TUFX's HDR and the clouds clipping, shouldn't be relevant to reborn itself but I'll leave it open.

**Comment by zhouyiqing0304** [comment]
@ballisticfo ty, and so what should i do

**Comment by zhouyiqing0304** [comment]
> This is a bug with TUFX's HDR and the clouds clipping, shouldn't be relevant to reborn itself but I'll leave it open.

tk, fixed
